name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  setup-and-linting:
    name: Setup Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: setup-and-linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Sonar Project File
        run: cat .sonar-project.properties

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=sonar

  docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Tag Docker Image
        run: |
          docker build -t mehedime91/next-japan:latest -t mehedime91/next-japan:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker Images
        run: |
          docker push mehedime91/next-japan:latest
          docker push mehedime91/next-japan:${{ steps.vars.outputs.sha_short }}

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: docker-image

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop next-japan || true
            docker rm next-japan || true
            docker pull mehedime91/next-japan:latest
            docker run -d \
              --name next-japan \
              -p 3000:3000 \
              --restart unless-stopped \
              mehedime91/next-japan:latest

  monitoring-setup:
    name: Setup Monitoring Stack (Prometheus + Grafana)
    runs-on: ubuntu-latest
    needs: deploy-to-ec2

    steps:
      - name: Connect to EC2 and set up monitoring stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system
            sudo apt update -y

            # Install Docker if not already installed
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sudo bash
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose plugin
            if ! command -v docker compose &> /dev/null; then
              sudo apt install docker-compose-plugin -y
            fi

            # Create monitoring directory
            mkdir -p ~/monitoring && cd ~/monitoring

            # Create docker-compose.yml
            cat > docker-compose.yml <<EOF
            version: '3'

            services:
              prometheus:
                image: prom/prometheus
                ports:
                  - "9090:9090"
                volumes:
                  - ./prometheus.yml:/etc/prometheus/prometheus.yml

              node-exporter:
                image: prom/node-exporter
                ports:
                  - "9100:9100"

              grafana:
                image: grafana/grafana
                ports:
                  - "3001:3000"
                environment:
                  - GF_SECURITY_ADMIN_USER=admin
                  - GF_SECURITY_ADMIN_PASSWORD=admin
                volumes:
                  - grafana-data:/var/lib/grafana

            volumes:
              grafana-data:
            EOF

            # Create prometheus.yml
            cat > prometheus.yml <<EOF
            global:
              scrape_interval: 15s

            scrape_configs:
              - job_name: 'prometheus'
                static_configs:
                  - targets: ['localhost:9090']

              - job_name: 'node-exporter'
                static_configs:
                  - targets: ['localhost:9100']
            EOF

            # Restart monitoring stack
            docker compose down
            docker compose up -d
