name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  setup-and-linting:
    name: Setup Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: setup-and-linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Sonar Project File
        run: cat .sonar-project.properties

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=sonar

  docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Tag Docker Image
        run: |
          docker build -t mehedime91/next-japan:latest -t mehedime91/next-japan:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker Images
        run: |
          docker push mehedime91/next-japan:latest
          docker push mehedime91/next-japan:${{ steps.vars.outputs.sha_short }}

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: docker-image

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop next-japan || true
            docker rm next-japan || true
            docker pull mehedime91/next-japan:latest
            docker run -d \
              --name next-japan \
              -p 3000:3000 \
              --restart unless-stopped \
              mehedime91/next-japan:latest
              
  monitoring-setup:
    name: Setup Monitoring Stack on EC2
    runs-on: ubuntu-latest
    needs: docker-image

    steps:
      - name: Install Monitoring Tools on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system
            sudo apt update -y
            sudo apt install -y curl wget tar software-properties-common
            
            # Install Node Exporter
            cd /opt
            wget https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
            tar -xvzf node_exporter-1.8.1.linux-amd64.tar.gz
            sudo mv node_exporter-1.8.1.linux-amd64/node_exporter /usr/local/bin/

            sudo tee /etc/systemd/system/node_exporter.service > /dev/null <<EOF
            [Unit]
            Description=Node Exporter
            After=network.target

            [Service]
            User=nobody
            ExecStart=/usr/local/bin/node_exporter

            [Install]
            WantedBy=default.target
            EOF

            sudo systemctl daemon-reexec
            sudo systemctl enable node_exporter
            sudo systemctl start node_exporter

            # Install Prometheus
            cd /opt
            wget https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
            tar -xvzf prometheus-2.52.0.linux-amd64.tar.gz
            sudo mv prometheus-2.52.0.linux-amd64 /opt/prometheus
            cd /opt/prometheus

            cat <<EOF | sudo tee /opt/prometheus/prometheus.yml
            global:
              scrape_interval: 15s
            scrape_configs:
              - job_name: 'node_exporter'
                static_configs:
                  - targets: ['localhost:9100']
            EOF
            nohup ./prometheus --config.file=prometheus.yml > prometheus.log 2>&1 &

            # Install Grafana
            sudo apt-get install -y gnupg2
            wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
            sudo apt update
            sudo apt install grafana -y
            sudo systemctl enable grafana-server
            sudo systemctl start grafana-server

